Resources:
  SampleApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      Description: A sample .NET Core application

  SampleApplicationEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName: 
        Ref: SampleApplication
      SolutionStackName: 64bit Amazon Linux 2 v3.1.2 running Docker

Outputs:
  EnvironmentName:
    Description: The name of the Elastic Beanstalk environment
    Value: 
      Ref: SampleApplicationEnvironment
